# Generated by Django 6.0.1 on 2026-02-01 20:35

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cinema', '0001_initial'),
        ('core', '0001_initial'),
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('schedule', models.DateTimeField(help_text='Takes start date and time of the slot')),
                ('end_time', models.TimeField(help_text='Takes end time of the slot')),
                ('price', models.PositiveIntegerField()),
                ('cinema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='cinema.cinema')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='core.language')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='movie.movie')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('schedule', 'movie', 'cinema'), name='unique_slot_per_movie_cinema_schedule')],
            },
        ),
    ]
