# Generated by Django 6.0.1 on 2026-02-04 06:55

import django.db.models.deletion
from django.utils import timezone
from django.db import migrations, models
from datetime import datetime

# Functions from the following migrations need manual copying.
# Move them and any dependencies into this file, then update the
# RunPython operations to refer to the local versions:
# apps.slot.migrations.0003_convert_end_schedule_to_datetime

def forwards(apps, schema_editor):
    Slot = apps.get_model("slot", "Slot")

    for slot in Slot.objects.all():
        if slot.end_schedule:
            continue

        start = slot.schedule

        slot.end_schedule = timezone.make_aware(
            datetime.combine(start.date(), start.time()),
            timezone.get_current_timezone(),
        )

        slot.save(update_fields=["end_schedule"])


class Migration(migrations.Migration):

    replaces = [('slot', '0001_initial'), ('slot', '0002_remove_slot_end_time_slot_end_schedule'), ('slot', '0003_convert_end_schedule_to_datetime'), ('slot', '0004_alter_slot_end_schedule')]

    dependencies = [
        ('cinema', '0001_initial'),
        ('core', '0001_initial'),
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('schedule', models.DateTimeField(help_text='Takes start date and time of the slot')),
                ('price', models.PositiveIntegerField()),
                ('cinema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='cinema.cinema')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='core.language')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='movie.movie')),
                ('end_schedule', models.DateTimeField(blank=True, help_text='Takes end date and time of the slot', null=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('schedule', 'movie', 'cinema'), name='unique_slot_per_movie_cinema_schedule')],
            },
        ),
        migrations.RunPython(forwards),
        migrations.AlterField(
            model_name='slot',
            name='end_schedule',
            field=models.DateTimeField(help_text='Takes end date and time of the slot'),
        ),
    ]
