# Generated by Django 6.0.1 on 2026-01-16 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slot', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slot',
            old_name='cinema_id',
            new_name='cinema',
        ),
        migrations.RenameField(
            model_name='slot',
            old_name='language_id',
            new_name='language',
        ),
        migrations.RenameField(
            model_name='slot',
            old_name='movie_id',
            new_name='movie',
        ),
    ]
