# Generated by Django 6.0.1 on 2026-01-19 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slot', '0002_rename_cinema_id_slot_cinema_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slot',
            name='price',
            field=models.PositiveIntegerField(),
        ),
    ]
