# Generated by Django 6.0.1 on 2026-01-19 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slot', '0003_alter_slot_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
