# Generated by Django 6.0.1 on 2026-01-20 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0004_alter_cinema_city_delete_city'),
        ('core', '0002_city_genre'),
        ('movie', '0003_delete_genre_alter_movie_genre'),
        ('slot', '0004_slot_is_active'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='slot',
            constraint=models.UniqueConstraint(fields=('date_time', 'movie', 'cinema'), name='unique_slot_per_movie_cinema_date_time'),
        ),
    ]
