# Generated by Django 6.0.1 on 2026-01-21 08:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0006_alter_cinema_city'),
        ('core', '0002_city_genre'),
        ('movie', '0004_alter_movie_genre_alter_movie_language'),
        ('slot', '0005_slot_unique_slot_per_movie_cinema_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slot',
            name='cinema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='cinema.cinema'),
        ),
        migrations.AlterField(
            model_name='slot',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='core.language'),
        ),
        migrations.AlterField(
            model_name='slot',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='movie.movie'),
        ),
    ]
