# Generated by Django 6.0.1 on 2026-01-22 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slot', '0006_alter_slot_cinema_alter_slot_language_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='buffer_time',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
