# Generated by Django 6.0.1 on 2026-01-27 21:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_default=datetime.datetime(2026, 1, 27, 21, 0, 43, 913010, tzinfo=datetime.timezone.utc), editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Maximum 50 characters are allowed', max_length=50, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_default=datetime.datetime(2026, 1, 27, 21, 0, 43, 913010, tzinfo=datetime.timezone.utc), editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Maximum 50 characters are allowed', max_length=50, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_default=datetime.datetime(2026, 1, 27, 21, 0, 43, 913010, tzinfo=datetime.timezone.utc), editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Maximum 50 characters are allowed', max_length=50, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
