# Generated by Django 6.0.1 on 2026-01-27 21:01

import datetime
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('booking', '0001_initial'), ('booking', '0002_initial')]

    initial = True

    dependencies = [
        ('slot', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_default=datetime.datetime(2026, 1, 27, 21, 0, 43, 913010, tzinfo=datetime.timezone.utc), editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('B', 'Booked'), ('C', 'Cancelled'), ('P', 'Pending')], default='P', max_length=1)),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='slot.slot')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_default=datetime.datetime(2026, 1, 27, 21, 0, 43, 913010, tzinfo=datetime.timezone.utc), editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seat_row', models.PositiveIntegerField(help_text='Specify row of the seat (1-indexed)', validators=[django.core.validators.MinValueValidator(1)])),
                ('seat_number', models.PositiveIntegerField(help_text='Specitfy position of the seat in the row (1-indexed)', validators=[django.core.validators.MinValueValidator(1)])),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='booking.booking')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
