# Generated by Django 6.0.1 on 2026-01-16 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='slot_id',
            new_name='slot',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='seat',
            old_name='booking_id',
            new_name='booking',
        ),
    ]
