# Generated by Django 6.0.1 on 2026-01-19 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_rename_slot_id_booking_slot_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seat',
            name='seat_number',
            field=models.PositiveIntegerField(),
        ),
    ]
