# Generated by Django 6.0.1 on 2026-01-20 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_alter_seat_seat_number'),
        ('slot', '0004_slot_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='slot.slot'),
        ),
    ]
