# Generated by Django 6.0.1 on 2026-01-20 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_seat_slot'),
        ('slot', '0004_slot_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seat',
            name='slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slot.slot'),
        ),
    ]
