# Generated by Django 6.0.1 on 2026-01-20 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_alter_seat_slot'),
        ('slot', '0004_slot_is_active'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='seat',
            constraint=models.UniqueConstraint(fields=('slot', 'seat_row', 'seat_number'), name='unique_seats_per_slot'),
        ),
    ]
