# Generated by Django 6.0.1 on 2026-01-20 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_seat_unique_seats_per_slot'),
        ('slot', '0005_slot_unique_slot_per_movie_cinema_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seat',
            name='slot',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='slot.slot'),
        ),
    ]
