# Generated by Django 6.0.1 on 2026-01-21 08:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_alter_seat_slot'),
        ('slot', '0005_slot_unique_slot_per_movie_cinema_date_time'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='slot.slot'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='seat',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='booking.booking'),
        ),
        migrations.AlterField(
            model_name='seat',
            name='slot',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='slot.slot'),
        ),
    ]
