# Generated by Django 6.0.1 on 2026-01-22 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_alter_booking_slot_alter_booking_user_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='seat',
            name='unique_seats_per_slot',
        ),
        migrations.RemoveField(
            model_name='seat',
            name='slot',
        ),
    ]
