# Generated by Django 6.0.1 on 2026-01-22 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0010_remove_seat_unique_seats_per_slot_remove_seat_slot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seat',
            name='seat_row',
            field=models.PositiveIntegerField(),
        ),
    ]
