# Generated by Django 6.0.1 on 2026-02-04 08:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('movie', '0001_initial'), ('movie', '0002_alter_movie_slug')]

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=250, unique=True)),
                ('description', models.TextField(blank=True)),
                ('duration', models.DurationField()),
                ('release_date', models.DateField()),
                ('cover_image', models.ImageField(blank=True, help_text="Optional movie's poster shown to users", null=True, upload_to='movie_covers/')),
                ('slug', models.SlugField(editable=False, unique=True)),
                ('genres', models.ManyToManyField(related_name='movies', to='core.genre')),
                ('languages', models.ManyToManyField(related_name='movies', to='core.language')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
