# Generated by Django 6.0.1 on 2026-01-27 20:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_default=datetime.datetime(2026, 1, 27, 20, 33, 23, 25799, tzinfo=datetime.timezone.utc), editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Maximum 250 characters are allowed', max_length=250, unique=True)),
                ('description', models.TextField(blank=True)),
                ('duration', models.DurationField()),
                ('release_date', models.DateField()),
                ('cover_image', models.ImageField(blank=True, help_text="Upload the movie's poster if exists", null=True, upload_to='movie_covers/')),
                ('slug', models.SlugField(editable=False, max_length=250, unique=True)),
                ('genre', models.ManyToManyField(related_name='movies', to='core.genre')),
                ('language', models.ManyToManyField(related_name='movies', to='core.language')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
