# Generated by Django 6.0.1 on 2026-01-16 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='genre_id',
            new_name='genre',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='language_id',
            new_name='language',
        ),
    ]
