# Generated by Django 6.0.1 on 2026-01-19 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_city_genre'),
        ('movie', '0002_rename_genre_id_movie_genre_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Genre',
        ),
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.ManyToManyField(to='core.genre'),
        ),
    ]
