# Generated by Django 6.0.1 on 2026-01-21 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_city_genre'),
        ('movie', '0003_delete_genre_alter_movie_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.ManyToManyField(related_name='movies', to='core.genre'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='language',
            field=models.ManyToManyField(related_name='movies', to='core.language'),
        ),
    ]
