# Generated by Django 6.0.1 on 2026-01-29 12:24

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cinema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Maximum 250 characters are allowed', max_length=250)),
                ('rows', models.PositiveIntegerField(help_text='Specify total rows of seats in the cinema, minimum 5 are required', validators=[django.core.validators.MinValueValidator(5)])),
                ('seats_per_row', models.PositiveIntegerField(help_text='Minimum 5 seats per row are required', validators=[django.core.validators.MinValueValidator(5)])),
                ('address', models.TextField()),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cinemas', to='core.city')),
            ],
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('seat_row', models.PositiveIntegerField(help_text='Specify row of the seat (1-indexed)', validators=[django.core.validators.MinValueValidator(1)])),
                ('seat_number', models.PositiveIntegerField(help_text='Specify position of the seat in the row (1-indexed)', validators=[django.core.validators.MinValueValidator(1)])),
                ('cinema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='cinema.cinema')),
            ],
        ),
        migrations.AddConstraint(
            model_name='cinema',
            constraint=models.UniqueConstraint(fields=('name', 'address', 'city'), name='unique_cinema_per_address_city'),
        ),
        migrations.AddConstraint(
            model_name='seat',
            constraint=models.UniqueConstraint(fields=('seat_row', 'seat_number', 'cinema'), name='unique_seat_per_cinema'),
        ),
    ]
