# Generated by Django 6.0.1 on 2026-01-27 21:00

import datetime
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cinema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_default=datetime.datetime(2026, 1, 27, 21, 0, 43, 913010, tzinfo=datetime.timezone.utc), editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Maximum 250 characters are allowed', max_length=250)),
                ('rows', models.PositiveIntegerField(help_text='Specify total rows of seats in the cinema, minimum 5 are required', validators=[django.core.validators.MinValueValidator(5)])),
                ('seats_per_row', models.PositiveIntegerField(help_text='Minimum 5 seats per row are required', validators=[django.core.validators.MinValueValidator(5)])),
                ('address', models.TextField()),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cinemas', to='core.city')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('name', 'address', 'city'), name='unique_cinema_per_address_city')],
            },
        ),
    ]
