# Generated by Django 6.0.1 on 2026-01-16 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cinema',
            old_name='city_id',
            new_name='city',
        ),
    ]
