# Generated by Django 6.0.1 on 2026-01-19 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0002_rename_city_id_cinema_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cinema',
            name='rows',
            field=models.PositiveIntegerField(),
        ),
    ]
