# Generated by Django 6.0.1 on 2026-01-20 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0004_alter_cinema_city_delete_city'),
        ('core', '0002_city_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cinema',
            name='seats_per_row',
            field=models.PositiveIntegerField(),
        ),
        migrations.AddConstraint(
            model_name='cinema',
            constraint=models.UniqueConstraint(fields=('name', 'address', 'city'), name='unique_cinema_per_address_city'),
        ),
    ]
