# Generated by Django 6.0.1 on 2026-01-21 08:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0005_alter_cinema_seats_per_row_and_more'),
        ('core', '0002_city_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cinema',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cinemas', to='core.city'),
        ),
    ]
